backend:
  name: github
  repo: ramosht/elionquintiliano.com

publish_mode: editorial_workflow
media_folder: "static/assets/img"
public_folder: "assets/img"

collections:
  - name: "portfolio"
    label: "Portfólio"
    folder: "portfolio"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { 
          label: "Título", 
          name: "title", 
          widget: "string" 
        }
      - { 
          label: "Date", 
          name: "date", 
          widget: "datetime", 
          format: "YYYY-MM-DD hh:mm:ss" 
        }
      - { 
          label: "Descrição", 
          name: "description", 
          widget: "string",
        }
      - { 
          label: "Category", 
          name: "category", 
          widget: "select", 
          options: ["Filmmaker", "Designer"]
        }
      - { 
          label: "Link Projeto", 
          name: "linkProjeto", 
          widget: "string",
        }
      - { 
          label: "Imagem Destacada", 
          name: "thumbnail", 
          widget: "string",
        }